#!/usr/bin/env python3
"""
H7 per-hurricane breakdown — is the pooled WH result driven mainly by Helene?

White House data exists for Helene and Milton only (no Debby WH), and Helene is
~90% of the WH comments, so a pooled WH-vs-Reddit / WH-vs-FB number is almost
entirely a Helene number. This script splits H7 by storm for BOTH scorers so we
can see where the effect actually lives, and where VADER and RoBERTa diverge.

Comment-level. WH = government_response; FB = Phillips comments; Reddit = community.
RoBERTa score = pos - neg (continuous, project convention). Effect size = rank-biserial.

Outputs docs/week6/h7_pooled_helene_check.md. Read-only on inputs.
"""
from pathlib import Path
import pandas as pd
from scipy.stats import mannwhitneyu

REPO = Path(__file__).resolve().parents[2]
PROC = REPO / "data" / "processed"
OUT = REPO / "docs" / "week6" / "h7_pooled_helene_check.md"
OUT.parent.mkdir(parents=True, exist_ok=True)


def load(name):
    df = pd.read_csv(PROC / name, low_memory=False)
    df["hurricane"] = df["hurricane"].str.lower()
    df["rob"] = df["roberta_pos"] - df["roberta_neg"]
    return df


wh = load("whitehouse_threads_comments_vader_roberta_topics_labeled.csv")
fb = load("facebook_comments_vader_roberta_topics_labeled.csv")
rd = load("reddit_relevant_comments_vader_roberta_topics_labeled.csv")

METHODS = [("VADER", "vader_compound"), ("RoBERTa", "rob")]
STORMS = ["helene", "milton"]  # no WH data for Debby


def rank_biserial(a, b):
    """r>0 => group a tends higher than b; <0 => a lower."""
    U, p = mannwhitneyu(a, b, alternative="two-sided")
    r = 2 * U / (len(a) * len(b)) - 1
    return r, p


def sig(p):
    return "" if p < 0.05 else " (n.s.)"


rows = []
for storm in STORMS:
    for mname, col in METHODS:
        w, f, r = wh[wh.hurricane == storm], fb[fb.hurricane == storm], rd[rd.hurricane == storm]
        r_fb, p_fb = rank_biserial(w[col], f[col])
        r_rd, p_rd = rank_biserial(w[col], r[col])
        rows.append((storm, mname, len(w), w[col].mean(),
                     r_fb, p_fb, r_rd, p_rd))

lines = ["# H7 Per-Hurricane Breakdown — Is the Pooled Result Helene-Driven?",
         "",
         "_Joint task (Jose + Angelo), per Prof. Roy's request. Auto-generated by "
         "`code/week6_figures/h7_per_hurricane.py`._",
         "",
         f"WH comments by storm: Helene {len(wh[wh.hurricane=='helene'])}, "
         f"Milton {len(wh[wh.hurricane=='milton'])} (no Debby WH). "
         f"Pooled WH is {len(wh[wh.hurricane=='helene'])/len(wh):.0%} Helene.",
         "",
         "Comment-level. r = rank-biserial (negative ⇒ WH lower/more negative than the comparison group).",
         "",
         "| Storm | Method | n(WH) | WH mean | WH vs FB (r, p) | WH vs Reddit (r, p) |",
         "|---|---|---|---|---|---|"]
for storm, mname, n, wmean, r_fb, p_fb, r_rd, p_rd in rows:
    lines.append(f"| {storm.title()} | {mname} | {n} | {wmean:+.3f} | "
                 f"{r_fb:+.3f}, {p_fb:.1e}{sig(p_fb)} | {r_rd:+.3f}, {p_rd:.1e}{sig(p_rd)} |")

lines += [
    "",
    "## Findings",
    "",
    "- **WH vs Reddit — driven by Helene.** Milton on its own is non-significant under "
    "*both* scorers (RoBERTa p≈0.12; VADER flips to WH *above* Reddit, p≈0.48). The pooled "
    "significant WH-vs-Reddit negativity is essentially the Helene comments.",
    "- **WH vs FB — holds in both storms under RoBERTa, but Helene inflates the pooled size.** "
    "Milton is independently significant under RoBERTa (r≈−0.30), so this is not *solely* Helene; "
    "however Helene's larger effect (r≈−0.49) plus ~8.5× more rows dominate the pooled figure. "
    "Under VADER, Milton WH-vs-FB is non-significant.",
    "- **VADER and RoBERTa diverge in opposite directions across storms.** VADER reads WH as mildly "
    "*positive* in absolute terms (Helene +0.02, Milton +0.06) and even slightly above Reddit for Milton; "
    "RoBERTa reads WH clearly *negative* (Helene −0.37, Milton −0.27). The 'WH more negative' claim is "
    "a RoBERTa result and should be labeled as such.",
    "",
    "## Recommendation",
    "",
    "Report H7 **per storm**, or at minimum flag in the paper/slides that the pooled WH-vs-Reddit "
    "effect rests on Helene and that Milton alone does not reach significance. Pooling across two "
    "storms with a ~90/10 size imbalance hides this.",
    "",
]

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT.relative_to(REPO)}")
for storm, mname, n, wmean, r_fb, p_fb, r_rd, p_rd in rows:
    print(f"{storm:7s} {mname:7s} n={n:4d} WHmean={wmean:+.3f} "
          f"FB r={r_fb:+.3f} p={p_fb:.1e} | RD r={r_rd:+.3f} p={p_rd:.1e}")
